[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "schema-wrapper"
version = "0.1.0"
description = "Schema wrapper classes for Mosaic"
readme = "README.md"
requires-python = ">=3.9"

# Add development dependencies
[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]

[tool.hatch.envs.test]
dependencies = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]

[tool.hatch.envs.test.scripts]
cov = "pytest --cov-report=term-missing --cov=. {args}"

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.pytest.ini_options]
testpaths = ["test"]
python_files = ["test_*.py"]
addopts = "-v"

[tool.coverage.run]
source = ["."]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
]

[tool.ruff]
line-length = 88
target-version = "py39"